### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by stefanstoeckigt** [Godzil/fusd#5]
I am getting the following error when i try to make fusd. 

`
make -C libfusd
make[1]: Entering directory '/home/garrison-admin/inteldevstack/fusd/libfusd'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/garrison-admin/inteldevstack/fusd/libfusd'
make -C kfusd
make[1]: Entering directory '/home/garrison-admin/inteldevstack/fusd/kfusd'
make -C /lib/modules/3.10.0-693.el7.x86_64/build SUBDIRS=/home/garrison-admin/inteldevstack/fusd/kfusd EXTRA_CFLAGS="-I/home/garrison-admin/inteldevstack/fusd/kfusd/../include -DGIT_DESCRIBE='\"v1.14-pre2\"'" V=1 modules
make[2]: Entering directory '/usr/src/kernels/3.10.0-693.el7.x86_64'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
mkdir -p /home/garrison-admin/inteldevstack/fusd/kfusd/.tmp_versions ; rm -f /home/garrison-admin/inteldevstack/fusd/kfusd/.tmp_versions/*
make -f scripts/Makefile.build obj=/home/garrison-admin/inteldevstack/fusd/kfusd
  gcc -Wp,-MD,/home/garrison-admin/inteldevstack/fusd/kfusd/.kfusd.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I./arch/x86/include -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -Wframe-larger-than=2048 -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/garrison-admin/inteldevstack/fusd/kfusd/../include -DGIT_DESCRIBE='"v1.14-pre2"'  -DMODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(kfusd)"  -D"KBUILD_MODNAME=KBUILD_STR(kfusd)" -c -o /home/garrison-admin/inteldevstack/fusd/kfusd/.tmp_kfusd.o /home/garrison-admin/inteldevstack/fusd/kfusd/kfusd.c
/home/garrison-admin/inteldevstack/fusd/kfusd/kfusd.c: In function ‘fusd_aio_write’:
/home/garrison-admin/inteldevstack/fusd/kfusd/kfusd.c:2439:34: error: dereferencing pointer to incomplete type
    return fusd_process_write(iocb->ki_filp,
                                  ^
/home/garrison-admin/inteldevstack/fusd/kfusd/kfusd.c:2442:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[3]: *** [/home/garrison-admin/inteldevstack/fusd/kfusd/kfusd.o] Error 1
make[2]: *** [_module_/home/garrison-admin/inteldevstack/fusd/kfusd] Error 2
make[2]: Leaving directory '/usr/src/kernels/3.10.0-693.el7.x86_64'
make[1]: *** [default] Error 2
make[1]: Leaving directory '/home/garrison-admin/inteldevstack/fusd/kfusd'
make: *** [default] Error 2
`

**Comment by stefanstoeckigt** [comment]
Problem solved after updating the kernel.

**Comment by Godzil** [comment]
Well that may does mean that 3.10.0 is not correctly supported, I will have a look

**Comment by Godzil** [comment]
Build for 3.10.x has been solved. Will be pushed in next release.

See #9
